####SENSORS#####

#Weather Information
- platform: yr
  name: Weather
  monitored_conditions:
    - temperature
    - symbol

#Purchase Balance of Sky
- platform: rest
  resource: http://192.168.0.15:9006/as/system/information
  method: GET
  value_template: '{{value_json.purchasebalance}}'
  name: sky_purchase_balance
