####SWITCHES####
#- platform: rest
#  resource: http://192.168.0.15:9006/as/system/information
#  body_on: '{"active": "true"}'
#  body_off: '{"active": "false"}'
#  is_on_template: '{% if  value_json.activeStandby | lower  =="false" %} true {%-else %} false {%- endif %}'
#  name: isskyqon

- platform: template
  switches:
    skyqstate:
      friendly_name: SkyQ On Off
      value_template: "{{ states.binary_sensor.is_skyq_on.state }}"
      turn_on:
        service: script.turn_on
        entity_id: script.poweron_skyq
      turn_off:
        service: script.turn_on
        entity_id: script.poweroff_skyq
